application: task-manager-angular
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /app
  static_dir: app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
